export const EVENT_TYPES = [
    "Não verificada",
    "Cancelado",
    "Acidente com vítima fatal",
    "Acidente com vítima",
    "Acidente sem vítima",
    "Atropelamento",
    "Queda acidental",
    "Semáforo apagado",
    "Semáforo conflitante",
    "Semáforo embandeirado",
    "Semáforo estacionado",
    "Semáforo intermitente",
    "Braço projetado abalroado",
    "Braço projetado danificado",
    "Braço projetado fora de posição",
    "Grupo focal abalroado ou danificado",
    "Grupo focal com risco de queda",
    "Grupo focal encoberto por vegetação",
    "Grupo focal fora de posição",
    "Botoeira com defeito",
    "Coluna abalroada",
    "Coluna com risco de queda",
    "Coluna danificada",
    "Coluna fora de posição",
    "Lampada queimada",
    "Painel com risco de queda",
    "Pestana ausente",
    "Pestana danificada",
    "Poste próprio abalroado",
    "Poste próprio com risco de queda",
    "Poste próprio danificado",
    "Poste próprio fora de posição",
    "Sem sincronismo",
    "Sinal sonoro disparado",
    "Sinalização horizontal ausente/apagada",
    "Sinalização vertical ausente",
    "Sinalização vertical caída",
    "Sinalização vertical com risco de queda",
    "Sinalização vertical danificada",
    "Sinalização vertical fora de posição",
    "Sinalização vertical ilegível",
    "Sinalização vertical inutilizada (vandalismo)",
    "Sinalização vertical conflitante",
    "Temporização curta",
    "Guia rebaixada",
    "R6a",
    "R6a camioneta/vans",
    "R6a carga/descarga",
    "R6a emb/desembarque",
    "R6a exceto credencial",
    "R6a feira livre",
    "R6a ônibus/caminhões",
    "R6a ônibus turístico",
    "R6a sanitário",
    "R6b 20min",
    "R6b ambulância",
    "R6b carga/descarga",
    "R6b deficiente",
    "R6b escolar",
    "R6b emb/desembarque",
    "R6b exceto credencial",
    "R6b farmácia",
    "R6b idoso",
    "R6b lotação",
    "R6b motos",
    "R6b táxi",
    "R6b zona azul",
    "R6c",
    "Afastado da guia",
    "Bloqueio de via",
    "Calçada",
    "Canteiro central ou praça",
    "Ciclovia",
    "Contra mão",
    "Em faixa de rolamento",
    "Esquina",
    "Estacionado no meio da via",
    "Faixa arenosa",
    "Faixa de pedestre",
    "Fila Dupla",
    "Hidrante",
    "Impedindo movimentação",
    "Marca de canalização",
    "Paralelo em vaga 45º",
    "Perpendicular a via",
    "Estacionado 45º",
    "Ponto de ônibus",
    "Rampa deficiente",
    "Rotatória",
    "Trilho do bonde ou VLT",
    "Automóvel quebrado",
    "Caminhão quebrado",
    "Ônibus quebrado",
    "Caminhão superdimensionado",
    "Apoio operacional",
    "Carga na via",
    "Incêndio",
    "Óleo na via",
    "Reserva de vagas irregular",
    "Trânsito lento",
    "Trânsito parado",
    "Bueiro com tampa afundada ou quebrada",
    "Bueiro sem tampa",
    "Bueiro tampa fora de posição",
    "Buraco",
    "Entulho na via",
    "PV sem tampa",
    "PV tampa afundada",
    "PV tampa quebrada",
    "PV tampa solta",
    "PV tampa fora de posição",
    "Solapamento",
    "Cabeamento abaixo da altura normal / caído",
    "Cabeamento em curto",
    "Caçamba irregular",
    "Falta de energia/Iluminação pública apagada",
    "Sinalização vertical encoberta por vegetação",
    "Transformador em falha/curto/combustão",
    "Vazamento água/esgoto",
    "Placa publicitária em local proibido ou fora de posição",
    "Placa publicitária com risco de queda",
    "Placa publicitária caída",
    "Reclamação de Transportes Públicos ou Serviços",
    "Placa ou pintura de solo fora do padrão",
    "Luminária com risco de queda/caída",
    "Alagamento",
    "Árvore com risco de queda",
    "Carroça irregular",
    "Marquise com risco de queda",
    "Queda de marquise",
    "Poste caído",
    "Poste com risco de queda",
    "Queda de árvore",
    "Veículo transitando em ZR",
    "Vazamento de combustível, gás ou produto químico",
    "Mal Súbito",
    "Interdição de calçada ou via sem autorização",
    "Queda da própria altura",
    "Recolhimento de material CET",
    "Faixa de publicidade encobrindo sinalização",
    "Estacionado 90º",
    "Problema semafórico (waze)"
  ];